// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: ../Client_2/Assets/Scripts/behaviac/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: Ai_Monster

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_Ai_Monster_node4 : behaviac.Condition
	{
		public Condition_bt_Ai_Monster_node4()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((ActorAI)pAgent).Ai_SelectEnemy();
			bool opr = true;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_Ai_Monster_node3 : behaviac.Condition
	{
		public Condition_bt_Ai_Monster_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((ActorAI)pAgent).Ai_SelectSkill();
			bool opr = true;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_Ai_Monster_node8 : behaviac.Action
	{
		public Action_bt_Ai_Monster_node8()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((ActorAI)pAgent).Ai_MoveToEnemy();
			return EBTStatus.BT_SUCCESS;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_Ai_Monster_node6 : behaviac.Action
	{
		public Action_bt_Ai_Monster_node6()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((ActorAI)pAgent).Ai_Attack();
			return EBTStatus.BT_SUCCESS;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_Ai_Monster_node7 : behaviac.Action
	{
		public Action_bt_Ai_Monster_node7()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((ActorAI)pAgent).Ai_SelectEnemy();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_Ai_Monster
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Ai_Monster");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("ActorAI");
#endif
			// children
			{
				Selector node0 = new Selector();
				node0.SetClassNameString("Selector");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("ActorAI");
#endif
				bt.AddChild(node0);
				{
					Sequence node1 = new Sequence();
					node1.SetClassNameString("Sequence");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("ActorAI");
#endif
					node0.AddChild(node1);
					{
						Condition_bt_Ai_Monster_node4 node4 = new Condition_bt_Ai_Monster_node4();
						node4.SetClassNameString("Condition");
						node4.SetId(4);
#if !BEHAVIAC_RELEASE
						node4.SetAgentType("ActorAI");
#endif
						node1.AddChild(node4);
						node1.SetHasEvents(node1.HasEvents() | node4.HasEvents());
					}
					{
						Selector node5 = new Selector();
						node5.SetClassNameString("Selector");
						node5.SetId(5);
#if !BEHAVIAC_RELEASE
						node5.SetAgentType("ActorAI");
#endif
						node1.AddChild(node5);
						{
							Condition_bt_Ai_Monster_node3 node3 = new Condition_bt_Ai_Monster_node3();
							node3.SetClassNameString("Condition");
							node3.SetId(3);
#if !BEHAVIAC_RELEASE
							node3.SetAgentType("ActorAI");
#endif
							node5.AddChild(node3);
							node5.SetHasEvents(node5.HasEvents() | node3.HasEvents());
						}
						{
							Action_bt_Ai_Monster_node8 node8 = new Action_bt_Ai_Monster_node8();
							node8.SetClassNameString("Action");
							node8.SetId(8);
#if !BEHAVIAC_RELEASE
							node8.SetAgentType("ActorAI");
#endif
							node5.AddChild(node8);
							node5.SetHasEvents(node5.HasEvents() | node8.HasEvents());
						}
						node1.SetHasEvents(node1.HasEvents() | node5.HasEvents());
					}
					{
						Action_bt_Ai_Monster_node6 node6 = new Action_bt_Ai_Monster_node6();
						node6.SetClassNameString("Action");
						node6.SetId(6);
#if !BEHAVIAC_RELEASE
						node6.SetAgentType("ActorAI");
#endif
						node1.AddChild(node6);
						node1.SetHasEvents(node1.HasEvents() | node6.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Sequence node2 = new Sequence();
					node2.SetClassNameString("Sequence");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("ActorAI");
#endif
					node0.AddChild(node2);
					{
						Action_bt_Ai_Monster_node7 node7 = new Action_bt_Ai_Monster_node7();
						node7.SetClassNameString("Action");
						node7.SetId(7);
#if !BEHAVIAC_RELEASE
						node7.SetAgentType("ActorAI");
#endif
						node2.AddChild(node7);
						node2.SetHasEvents(node2.HasEvents() | node7.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: Ai_Partner

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_Ai_Partner_node4 : behaviac.Condition
	{
		public Condition_bt_Ai_Partner_node4()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((ActorAI)pAgent).Ai_SelectEnemy();
			bool opr = true;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_Ai_Partner_node9 : behaviac.Condition
	{
		public Condition_bt_Ai_Partner_node9()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((ActorAI)pAgent).Ai_ToFarFromHost();
			bool opr = false;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_Ai_Partner_node3 : behaviac.Condition
	{
		public Condition_bt_Ai_Partner_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((ActorAI)pAgent).Ai_SelectSkill();
			bool opr = true;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_Ai_Partner_node8 : behaviac.Action
	{
		public Action_bt_Ai_Partner_node8()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((ActorAI)pAgent).Ai_MoveToEnemy();
			return EBTStatus.BT_SUCCESS;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_Ai_Partner_node6 : behaviac.Action
	{
		public Action_bt_Ai_Partner_node6()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((ActorAI)pAgent).Ai_Attack();
			return EBTStatus.BT_SUCCESS;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_Ai_Partner_node7 : behaviac.Action
	{
		public Action_bt_Ai_Partner_node7()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((ActorAI)pAgent).Ai_FollowHost();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_Ai_Partner
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Ai_Partner");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("ActorAI");
#endif
			// children
			{
				Selector node0 = new Selector();
				node0.SetClassNameString("Selector");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("ActorAI");
#endif
				bt.AddChild(node0);
				{
					Sequence node1 = new Sequence();
					node1.SetClassNameString("Sequence");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("ActorAI");
#endif
					node0.AddChild(node1);
					{
						Condition_bt_Ai_Partner_node4 node4 = new Condition_bt_Ai_Partner_node4();
						node4.SetClassNameString("Condition");
						node4.SetId(4);
#if !BEHAVIAC_RELEASE
						node4.SetAgentType("ActorAI");
#endif
						node1.AddChild(node4);
						node1.SetHasEvents(node1.HasEvents() | node4.HasEvents());
					}
					{
						Condition_bt_Ai_Partner_node9 node9 = new Condition_bt_Ai_Partner_node9();
						node9.SetClassNameString("Condition");
						node9.SetId(9);
#if !BEHAVIAC_RELEASE
						node9.SetAgentType("ActorAI");
#endif
						node1.AddChild(node9);
						node1.SetHasEvents(node1.HasEvents() | node9.HasEvents());
					}
					{
						Selector node5 = new Selector();
						node5.SetClassNameString("Selector");
						node5.SetId(5);
#if !BEHAVIAC_RELEASE
						node5.SetAgentType("ActorAI");
#endif
						node1.AddChild(node5);
						{
							Condition_bt_Ai_Partner_node3 node3 = new Condition_bt_Ai_Partner_node3();
							node3.SetClassNameString("Condition");
							node3.SetId(3);
#if !BEHAVIAC_RELEASE
							node3.SetAgentType("ActorAI");
#endif
							node5.AddChild(node3);
							node5.SetHasEvents(node5.HasEvents() | node3.HasEvents());
						}
						{
							Action_bt_Ai_Partner_node8 node8 = new Action_bt_Ai_Partner_node8();
							node8.SetClassNameString("Action");
							node8.SetId(8);
#if !BEHAVIAC_RELEASE
							node8.SetAgentType("ActorAI");
#endif
							node5.AddChild(node8);
							node5.SetHasEvents(node5.HasEvents() | node8.HasEvents());
						}
						node1.SetHasEvents(node1.HasEvents() | node5.HasEvents());
					}
					{
						Action_bt_Ai_Partner_node6 node6 = new Action_bt_Ai_Partner_node6();
						node6.SetClassNameString("Action");
						node6.SetId(6);
#if !BEHAVIAC_RELEASE
						node6.SetAgentType("ActorAI");
#endif
						node1.AddChild(node6);
						node1.SetHasEvents(node1.HasEvents() | node6.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Sequence node2 = new Sequence();
					node2.SetClassNameString("Sequence");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("ActorAI");
#endif
					node0.AddChild(node2);
					{
						Action_bt_Ai_Partner_node7 node7 = new Action_bt_Ai_Partner_node7();
						node7.SetClassNameString("Action");
						node7.SetId(7);
#if !BEHAVIAC_RELEASE
						node7.SetAgentType("ActorAI");
#endif
						node2.AddChild(node7);
						node2.SetHasEvents(node2.HasEvents() | node7.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: Ai_Pet

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_Ai_Pet_node4 : behaviac.Condition
	{
		public Condition_bt_Ai_Pet_node4()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((ActorAI)pAgent).Ai_SelectEnemy();
			bool opr = true;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_Ai_Pet_node3 : behaviac.Condition
	{
		public Condition_bt_Ai_Pet_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((ActorAI)pAgent).Ai_SelectSkill();
			bool opr = true;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_Ai_Pet_node8 : behaviac.Action
	{
		public Action_bt_Ai_Pet_node8()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((ActorAI)pAgent).Ai_MoveToEnemy();
			return EBTStatus.BT_SUCCESS;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_Ai_Pet_node6 : behaviac.Action
	{
		public Action_bt_Ai_Pet_node6()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((ActorAI)pAgent).Ai_Attack();
			return EBTStatus.BT_SUCCESS;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_Ai_Pet_node7 : behaviac.Action
	{
		public Action_bt_Ai_Pet_node7()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((ActorAI)pAgent).Ai_SelectEnemy();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_Ai_Pet
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Ai_Pet");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("ActorAI");
#endif
			// children
			{
				Selector node0 = new Selector();
				node0.SetClassNameString("Selector");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("ActorAI");
#endif
				bt.AddChild(node0);
				{
					Sequence node1 = new Sequence();
					node1.SetClassNameString("Sequence");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("ActorAI");
#endif
					node0.AddChild(node1);
					{
						Condition_bt_Ai_Pet_node4 node4 = new Condition_bt_Ai_Pet_node4();
						node4.SetClassNameString("Condition");
						node4.SetId(4);
#if !BEHAVIAC_RELEASE
						node4.SetAgentType("ActorAI");
#endif
						node1.AddChild(node4);
						node1.SetHasEvents(node1.HasEvents() | node4.HasEvents());
					}
					{
						Selector node5 = new Selector();
						node5.SetClassNameString("Selector");
						node5.SetId(5);
#if !BEHAVIAC_RELEASE
						node5.SetAgentType("ActorAI");
#endif
						node1.AddChild(node5);
						{
							Condition_bt_Ai_Pet_node3 node3 = new Condition_bt_Ai_Pet_node3();
							node3.SetClassNameString("Condition");
							node3.SetId(3);
#if !BEHAVIAC_RELEASE
							node3.SetAgentType("ActorAI");
#endif
							node5.AddChild(node3);
							node5.SetHasEvents(node5.HasEvents() | node3.HasEvents());
						}
						{
							Action_bt_Ai_Pet_node8 node8 = new Action_bt_Ai_Pet_node8();
							node8.SetClassNameString("Action");
							node8.SetId(8);
#if !BEHAVIAC_RELEASE
							node8.SetAgentType("ActorAI");
#endif
							node5.AddChild(node8);
							node5.SetHasEvents(node5.HasEvents() | node8.HasEvents());
						}
						node1.SetHasEvents(node1.HasEvents() | node5.HasEvents());
					}
					{
						Action_bt_Ai_Pet_node6 node6 = new Action_bt_Ai_Pet_node6();
						node6.SetClassNameString("Action");
						node6.SetId(6);
#if !BEHAVIAC_RELEASE
						node6.SetAgentType("ActorAI");
#endif
						node1.AddChild(node6);
						node1.SetHasEvents(node1.HasEvents() | node6.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Sequence node2 = new Sequence();
					node2.SetClassNameString("Sequence");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("ActorAI");
#endif
					node0.AddChild(node2);
					{
						Action_bt_Ai_Pet_node7 node7 = new Action_bt_Ai_Pet_node7();
						node7.SetClassNameString("Action");
						node7.SetId(7);
#if !BEHAVIAC_RELEASE
						node7.SetAgentType("ActorAI");
#endif
						node2.AddChild(node7);
						node2.SetHasEvents(node2.HasEvents() | node7.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
